### PR TITLE
Convert the new osu!beatmap links to the old one as a workaround

### PR DESCRIPTION
**Pull request by touanu**
This makes osumer detect the new format of osu!beatmap ("https://osu.ppy.sh/beatmapsets" and "https://osu.ppy.sh/beatmaps")
Also fix "Could not connect or add queue to daemon" issue when trying to download a map from game at Daemon.java

Remove "jackson" jar from osumer-setup.vdproj

### CODE REVIEW

**Comment by SuperMario22922** [comment]
Could I please have an installer for this

**Comment by touanu** [comment]
> Could I please have an installer for this

You can get it from my repo

**Comment by SuperMario22922** [comment]
Thank you so much for this!

**Comment by a1aw** [comment]
@touanu sorry for abandoning this project for years. I will look into your pull request and merge it asap thxx!

**Comment by touanu** [comment]
that would be nice :D

**Comment by a1aw** [comment]
I think it is okay. But the problem is we need to update the build version that is hard-coded in Osumer.java and osumer-setup.vdproject

https://github.com/mob41/osumer/blob/master/pom.xml
    - `global.build` to 11
https://github.com/mob41/osumer/blob/master/osumer-lib/src/main/java/com/github/mob41/osumer/Osumer.java
    - `OSUMER_BUILD_NUM` to 11
https://github.com/mob41/osumer/blob/master/osumer-setup/osumer-setup.vdproj
    - `ProductVersion` to 8:2.0.11

I think it is time for me to tidy up the repository for future contribution though. IMO, I am not really satisified with the code style that I had over 5 years ago. It needs to be momre documented and tidied.

After modifying these parameters, releasing the new setup, and updating the https://github.com/mob41/osumer-updater/blob/gh-pages/versions.json, update can be distributed to clients.

I can update the the json file and release the setup for you, but the parameters you might need to help me to change because it's in your fork. Thanks alot !

**Comment by touanu** [comment]
Updated it :D

**Comment by a1aw** [comment]
Sorry for late reply. Thanks a lot! I will release to GitHub soon.

**Comment by a1aw** [comment]
Released

**Pull request merged**
